# Generated by Django 3.1.3 on 2020-11-22 17:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 11, 22, 17, 47, 29, 933837, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='follower',
            name='blog',
            field=models.ManyToManyField(to='blog.PersonalBlog', verbose_name='blog'),
        ),
    ]
