# Generated by Django 3.1.3 on 2020-11-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201122_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='add_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
